services:
  backend:
    build:
      context: .
    container_name: crm-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/crm
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 
    depends_on:
      db:
        condition: service_started

  db:
    image: mysql:8.0
    container_name: crm-database
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: crm
      # MYSQL_ROOT_PASSWORD: 
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    volumes:
      - ./base/script.sql:/docker-entrypoint-initdb.d/schema.sql
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata:


